// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "github.com/emadghaffari/kit-blog/comments/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	StoreEndpoint  endpoint.Endpoint
	UpdateEndpoint endpoint.Endpoint
	ListEndpoint   endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.CommentsService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		ListEndpoint:   MakeListEndpoint(s),
		StoreEndpoint:  MakeStoreEndpoint(s),
		UpdateEndpoint: MakeUpdateEndpoint(s),
	}
	for _, m := range mdw["Store"] {
		eps.StoreEndpoint = m(eps.StoreEndpoint)
	}
	for _, m := range mdw["Update"] {
		eps.UpdateEndpoint = m(eps.UpdateEndpoint)
	}
	for _, m := range mdw["List"] {
		eps.ListEndpoint = m(eps.ListEndpoint)
	}
	return eps
}
