// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/emadghaffari/kit-blog/comments/pkg/endpoint"
	pb "github.com/emadghaffari/kit-blog/comments/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	store  grpc.Handler
	update grpc.Handler
	list   grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.CommentsServer {
	return &grpcServer{
		list:   makeListHandler(endpoints, options["List"]),
		store:  makeStoreHandler(endpoints, options["Store"]),
		update: makeUpdateHandler(endpoints, options["Update"]),
	}
}
